# Lincoln Dark - Coding Challenge 10 - April 18th, 2022
# The first step is importing necessary packages and setting our workspace, so our script knows where to find the data


# Next, we can use the raster calculator tool in the ArcGIS Pro modelbuilder, then export our model to python code.
# Below is the exported code, with modifications to output destinations to make it run smoothly.
# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-04-18 12:15:02
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Documents\ArcGIS\Projects\CC10\CC10.gdb", workspace=r"C:\Users\14017\Documents\ArcGIS\Projects\CC10\CC10.gdb"):
        LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20150201_20170301_01_T1_B5.tif")
        LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20150201_20170301_01_T1_B4.tif")
        LC08_L1TP_012031_20150422_20170301_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20150422_20170301_01_T1_B5.tif")
        LC08_L1TP_012031_20150422_20170301_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20150422_20170301_01_T1_B4.tif")
        LC08_L1TP_012031_20150508_20170227_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20150508_20170227_01_T1_B5.tif")
        LC08_L1TP_012031_20150508_20170227_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20150508_20170227_01_T1_B4.tif")
        LC08_L1TP_012031_20150711_20170226_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20150711_20170226_01_T1_B5.tif")
        LC08_L1TP_012031_20150711_20170226_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20150711_20170226_01_T1_B4.tif")
        LC08_L1TP_012031_20151015_20170225_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20151015_20170225_01_T1_B5.tif")
        LC08_L1TP_012031_20151015_20170225_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20151015_20170225_01_T1_B4.tif")
        LC08_L1TP_012031_20151116_20170225_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20151116_20170225_01_T1_B5.tif")
        LC08_L1TP_012031_20151116_20170225_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20151116_20170225_01_T1_B4.tif")

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        Feb_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\feb_nvdi"
        Raster_Calculator_2_ = Feb_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201502", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201502"):
            Feb_NVDI = ( LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif - LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif)/( LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif + LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif)
            Feb_NVDI.save(Raster_Calculator_2_)


        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        Apr_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\apr_nvdi"
        Raster_Calculator_3_ = Apr_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201504", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201504"):
            Apr_NVDI =  (LC08_L1TP_012031_20150422_20170301_01_T1_B5_tif - LC08_L1TP_012031_20150422_20170301_01_T1_B4_tif)/( LC08_L1TP_012031_20150422_20170301_01_T1_B5_tif + LC08_L1TP_012031_20150422_20170301_01_T1_B4_tif)
            Apr_NVDI.save(Raster_Calculator_3_)


        # Process: Raster Calculator (4) (Raster Calculator) (ia)
        May_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\may_nvdi"
        Raster_Calculator_4_ = May_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201505", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201505"):
            May_NVDI = ( LC08_L1TP_012031_20150508_20170227_01_T1_B5_tif - LC08_L1TP_012031_20150508_20170227_01_T1_B4_tif)/( LC08_L1TP_012031_20150508_20170227_01_T1_B5_tif + LC08_L1TP_012031_20150508_20170227_01_T1_B4_tif)
            May_NVDI.save(Raster_Calculator_4_)


        # Process: Raster Calculator (5) (Raster Calculator) (ia)
        Sep_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\sep_nvdi"
        Raster_Calculator_5_ = Sep_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201507", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201507"):
            Sep_NVDI = ( LC08_L1TP_012031_20150711_20170226_01_T1_B5_tif - LC08_L1TP_012031_20150711_20170226_01_T1_B4_tif)/( LC08_L1TP_012031_20150711_20170226_01_T1_B4_tif + LC08_L1TP_012031_20150711_20170226_01_T1_B5_tif)
            Sep_NVDI.save(Raster_Calculator_5_)


        # Process: Raster Calculator (6) (Raster Calculator) (ia)
        Oct_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\oct_nvdi"
        Raster_Calculator_6_ = Oct_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201510", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201510"):
            Oct_NVDI = ( LC08_L1TP_012031_20151015_20170225_01_T1_B5_tif - LC08_L1TP_012031_20151015_20170225_01_T1_B4_tif)/( LC08_L1TP_012031_20151015_20170225_01_T1_B5_tif + LC08_L1TP_012031_20151015_20170225_01_T1_B4_tif)
            Oct_NVDI.save(Raster_Calculator_6_)


        # Process: Raster Calculator (7) (Raster Calculator) (ia)
        Nov_NVDI = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\nov_nvdi"
        Raster_Calculator_7_ = Nov_NVDI
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201511", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\201511"):
            Nov_NVDI = ( LC08_L1TP_012031_20151116_20170225_01_T1_B5_tif - LC08_L1TP_012031_20151116_20170225_01_T1_B4_tif)/( LC08_L1TP_012031_20151116_20170225_01_T1_B5_tif + LC08_L1TP_012031_20151116_20170225_01_T1_B4_tif)
            Nov_NVDI.save(Raster_Calculator_7_)

        print(Feb_NVDI)
        print(Apr_NVDI)
        print(May_NVDI)
        print(Sep_NVDI)
        print(Oct_NVDI)
        print(Nov_NVDI)







