# Lincoln Dark - Coding Challenge 10 - April 18th, 2022
# The first step is importing necessary packages and setting our workspace, so our script knows where to find the data
import arcpy
arcpy.env.workspace = r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\Step_2_data\Winter_2015"
# Next, we can use the raster calculator tool in the ArcGIS Pro modelbuilder, then export our model to python code.
# Below is the exported code, with modifications to make it run smoothly.
# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-04-18 10:45:50
"""

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\Step_2_data\Winter_2015", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\Step_2_data\Winter_2015"):
        LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif = arcpy.Raster("LC08_L1TP_012031_20150201_20170301_01_T1_B5.tif")
        LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif = arcpy.Raster("LC08_L1TP_012031_20150201_20170301_01_T1_B4.tif")

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        CC10_Output = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC10\\Landsat_data_lfs\\Step_2_data\\Winter_2015"
        Raster_Calculator_2_ = CC10_Output
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\Step_2_data\Winter_2015", workspace=r"C:\Users\14017\Desktop\NRS_528\Github\CC10\Landsat_data_lfs\Step_2_data\Winter_2015"):
            CC10_Output =  (LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif - LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif) /( LC08_L1TP_012031_20150201_20170301_01_T1_B5_tif + LC08_L1TP_012031_20150201_20170301_01_T1_B4_tif)
            CC10_Output.save(Raster_Calculator_2_)






