import os
os.mkdir("E://draft_code")
os.mkdir("E://draft_code/pending")
os.mkdir("E://draft_code/complete")
os.mkdir("E://includes")
os.mkdir("E://layouts")
os.mkdir("E://layouts//default")
os.mkdir("E://layouts//post")
os.mkdir("E://layouts//post//posted")
os.mkdir("E://site")

os.rmdir("E://draft_code")
os.rmdir("E://draft_code/pending")
os.rmdir("E://draft_code/complete")
os.rmdir("E://includes")
os.rmdir("E://layouts")
os.rmdir("E://layouts//default")
os.rmdir("E://layouts//post")
os.rmdir("E://layouts//post//posted")
os.rmdir("E://site")
