# Coding Challenge 9 - April 13th 2022 - Lincoln Dark
# Data Prep
import arcpy
arcpy.env.workspace = r"C:\Users\14017\Desktop\NRS_528\Github\CC9"
input_shp = 'RI_Forest_Health_Works_Project%3A_Points_All_Invasives.shp'
fields = ['photo']
# Part 1 - Counting records with and without photos.
expression = arcpy.AddFieldDelimiters(input_shp, "photo") + " LIKE  'y%'" # This queries all rows in the photo field
# that have a value of "y", indicating that they have photos.
count = 0
with arcpy.da.SearchCursor(input_shp, fields, expression) as cursor:
    for row in cursor:
        count = count + 1
print(count)

NoPhotos = arcpy.AddFieldDelimiters(input_shp, "photo") + " LIKE '%'" # This queries all rows in the photo field.
count1 = 0
with arcpy.da.SearchCursor(input_shp, fields, NoPhotos) as cursor:
    for row in cursor:
        count1 = count1 + 1
print(count1 - count) # This line substracts the number of rows with photos from the overall number, telling us the
# number of rows that do not have photos.

# Part 2 - Counting the number of unique species
species_list = []
with arcpy.da.SearchCursor(input_shp, ['Species']) as cursor: # This queries only the Species row
    for row in cursor:
        if row[0] not in species_list:
            species_list.append(row[0]) # If a unique species has not appeared in the field yet, this line adds it to
            # our list of species.
print(len(species_list)) # Here, we print the length of the species list, because if we just print the species list,
# it will show us the names of each species. However, we want to know the number of species

# Part 3 - Generating two shapefiles, one with photos and one without
# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-04-14 11:28:43
"""
import arcpy

def Model1():  # Model 1
    arcpy.env.overwriteOutput = False
arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
RI_Forest_Health_Works_Project_3A_Points_All_Invasives = "RI_Forest_Health_Works_Project%3A_Points_All_Invasives"
CC9_2_ = "C:\\Users\\14017\\Desktop\\NRS_528\\Github\\CC9"

y = "C:\\Users\\14017\\Documents\\ArcGIS\\Projects\\MyProject7\\MyProject7.gdb\\y"
arcpy.analysis.Select(in_features=RI_Forest_Health_Works_Project_3A_Points_All_Invasives, out_feature_class=y, where_clause="photo = 'y'")

CC9 = arcpy.conversion.FeatureClassToShapefile(Input_Features=[y], Output_Folder=CC9_2_)[0]

not_y = "C:\\Users\\14017\\Documents\\ArcGIS\\Projects\\MyProject7\\MyProject7.gdb\\not_y"
arcpy.analysis.Select(in_features=RI_Forest_Health_Works_Project_3A_Points_All_Invasives, out_feature_class=not_y, where_clause="photo <> 'y'")

Updated_Output_Folder_2_ = arcpy.conversion.FeatureClassToShapefile(Input_Features=[not_y], Output_Folder=CC9_2_)[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\14017\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=r"C:\Users\14017\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb"):
        Model1()

# Code sourced from ArcGIS Pro
